package com.example.backend.entity.item.enums;

public enum SubcategoryEnum {
    SHORT_TSHIRT,
    LONG_TSHIRT,
    BASIC_SHIRT,
    BLOUSE,
    KNIT,
    GARDIGAN,
    HOODIE,
    MANTOMAN,
    DENIM_PANTS,
    SLACKS,
    DENUM_SHORT,
    COTTON_SHORT,
    MINI_SKIRT,
    LONG_SKIRT,
    JAKET,
    JUMPER,
    COAR,
    PADDING,
    MINI_DRESS,
    LONG_DRESS,
    JUMPSUIT,
    OVERALLS,
    LOW_SNEAKERS,
    HIGH_SNEAKERS,
    FLAT_SHOES,
    HEEL,
    BOOTS,
    SANDLE,
    TOOE_BAG,
    CROSS_BAG,
    HAT,
    BELT;
}
